### ISSUE TITLE
✨ [Feat] 게시글 내 더보기 기능(스타일) 적용 

### ISSUE THREAD

**Issue by rachelyu1025** [Co-Run-Toy-Project/costagram#118]
## Description

제한된 글자 수(혹은 width) 에 따라 작성된 게시글이 보이도록 구현합니다. 
글자 수를 넘어가면 더보기 버튼 활성화 및 text overflow 스타일을 적용해줍니다. 

## Todo

- [ ] 제한된 기준에 따라 더보기 버튼을 활성화/비활성화 시킵니다.(조건부 적용) 
- [ ] 제한된 기준을 넘어서면, text overflow 스타일을 적용합니다. (truncate 적용 예정) 
- [ ] 더보기 버튼 클릭 시 전체 내용을 보여줍니다. 

## ETC
- 주의 사항 혹은 기타 내용
