### ISSUE TITLE
✨ [Feat] 컨트롤러 구현

### ISSUE THREAD

**Issue by dorrion** [Co-Run-Toy-Project/costagram#34]
## Description

컨트롤러 구현 + db 저장 기능 구현
(이슈 작성 안하고 작업하던 거 뒤늦게 깨달아서 이슈 작성합니다)

## Todo

- [ ] 게시물 관련 컨트롤러 구현 
- [ ] 유저 관련 컨트롤러 구현 
- [ ] 댓글 관련 컨트롤러 구현
- [ ] 좋아요 관련 컨트롤러 구현

## ETC
- 주의 사항 혹은 기타 내용
잘못된 컨트롤러 구현할까봐 걱정되지만 최대한 신속하게 진행하기..!
