### ISSUE TITLE
✨ [Feat] 게시글 등록 모달 구현

### ISSUE THREAD

**Issue by rachelyu1025** [Co-Run-Toy-Project/costagram#5]
## Description

게시글 등록 시 뜨게될 모달창을 구현합니다. 

## Todo

- [x] 모달 레이아웃 퍼블리싱 
- [x] 모달 레이아웃 반응형 퍼블리싱 
- [x] 뒤로가기 버튼(아이콘) 클릭 시 모달 닫히도록 구현 

## ETC
- 주의 사항 혹은 기타 내용
